baseurl = "http://localhost:1313/"
languageCode = "en-us"
title = "Musicians of the San Antonio Symphony"
theme = "purehugo"
Paginate = 10
buildDrafts = true

[params]
  description = "News and Info about the People of the Symphony."
  twitter = "@sasmusicians"
  facebook = "sasmusicians"
